correct domains for adobe, aws, atlassian, google, oracle, segment rules
Privado-Inc/privado pull request #172
Opened 2023-02-20 15:41 UTC by hiaashna

2023-02-21 06:38 UTC, abhstabs requested changes

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/adobe/java.yaml
> +      - "www.adobe.com/products/xd"
The www prefix can be removed

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/amazonaws/java.yaml
> +      - "www.honeycode.aws/"
prefix can be omitted

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/amazonaws/java.yaml
> +      - "www.amazonaws.cn/en/msk/"
Prefix can be omitted

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/en-us/iaas/tools/java/3.4.0/com/oracle/bmc/common"
Can you confirm if this URL is correct? Also, the rule looks like an SDK common library instead of a product. Remove if needed.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/en-us/iaas/tools/java/3.4.0/com/oracle/bmc/http"
Looks like a link to a library javadoc instead of a product. Remove if needed.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/en-us/iaas/tools/java/3.4.0/com/oracle/bmc/internal"
Looks like a link to a library javadoc instead of a product. Remove if needed.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - ".oracle.com/"
Incorrect Domain. Please check and correct.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - ".oracle.com/en-us/iaas/Content/KeyManagement/"
incorrect domain. Please check and correct.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/"
Domain looks too broad.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - ".oracle.com/en-us/iaas/pl-sql-sdk/doc/dbms_cloud_oci_ws_waas."
Incorrect domain

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/en-us/iaas/tools/java/3.4.0/com/oracle/bmc/functions"
Looks like a link to a library javadoc instead of a product. Use the link to product/service instead.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/database/technologies/oraclecertificationenvironment."
incorrect domain. "." at the end.

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - "oracle.com/database/technologies/database-appliance."
incorrect domain format

2023-02-21 06:38 UTC, abhstabs commented on rules/sinks/third_parties/sdk/oracle/java.yaml
> +      - ".oracle.com/en-us/iaas/Content/APIGateway/Concepts/apigatewayoverview."
"." at beginning and end

2023-02-22 03:47 UTC, hiaashna commented on rules/sinks/third_parties/sdk/adobe/java.yaml
> +      - "www.adobe.com/products/xd"
removed

2023-02-22 03:48 UTC, hiaashna commented on rules/sinks/third_parties/sdk/amazonaws/java.yaml
> +      - "www.honeycode.aws/"
removed

2023-02-22 03:48 UTC, hiaashna commented on rules/sinks/third_parties/sdk/amazonaws/java.yaml
> +      - "www.amazonaws.cn/en/msk/"
removed

2023-02-22 07:13 UTC, abhstabs approved these changes

2023-02-22 07:13 UTC, merged